default: &default
  adapter: postgresql
  encoding: unicode
  username: umineco
  database: umineco
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: umineco_test
